[build]
  command = "npm install -g @angular/cli && cd securetimenotes-frontend/securetimenotes && npm install && ng build --configuration=production --base-href /"
  publish = "securetimenotes-frontend/securetimenotes/dist/securetimenotes"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
