[build]
  base = "securetimenotes-frontend/securetimenotes"
  command = "npm install && ng build --configuration=production"
  publish = "dist/securetimenotes"

[[redirects]]
  from = "/*"
  to = "./browser/index.html"
  status = 200
  force = true
  
