[build]
  base = "securetimenotes-frontend/securetimenotes"
  command = "npm install && ng build --configuration=production --base-href /"
  publish = "../../securetimenotes/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
