[build]
  base = "securetimenotes-frontend"
  command = "npm install && ng build --configuration=production --base-href /"
  publish = "securetimenotes-frontend/dist/securetimenotes"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
