[build]
  base = "securetimenotes-frontend/securetimenotes"
  command = "npm install && ng build --configuration=production --base-href /"
  publish = "dist/securetimenotes"

[[redirects]]
  from = "/*"
  to = "./browser/index.html"
  status = 200

  
